services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build:
      dockerfile: Dockerfile
    container_name: dog-clicker-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/${POSTGRESQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRESQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - "8090:8080"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    name: dog_clicker_net
