--liquibase formatted sql

--changeset andrii.kolomoiets:01-create-settings-table
CREATE TABLE settings
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sound BOOLEAN      NOT NULL,
    music BOOLEAN      NOT NULL
);
